export interface AppRelease {
  audience: 'app' | 'admin';
  version: string;
  date: string;
  title: string;
  summary: string;
  important: boolean;
  changes: string[];
}

const RELEASES: AppRelease[] = [
  {
    audience: 'app',
    version: '1.18.0',
    date: '2026-09-09',
    title: 'Projection vidéo',
    summary: 'Les vidéos rejoignent les pads avec une fenêtre de projection séparée.',
    important: false,
    changes: [
      'Import MP4 et WebM, miniatures et filtre audio/vidéo dans la bibliothèque.',
      'Projection sur une fenêtre séparée avec aperçu, pause, arrêt et noir écran.',
      'Points d’entrée et de sortie, boucle, volume et conservation de la dernière image.',
      'Téléchargement hors ligne des vidéos et commandes depuis la télécommande.',
      'Une seule projection à la fois ; les playlists restent audio et le son vidéo utilise la sortie système du navigateur.',
    ],
  },
  {
    audience: 'app',
    version: '1.17.0',
    date: '2026-09-06',
    title: 'Notifications de souscription',
    summary: 'Les nouvelles activations de forfait alimentent désormais les alertes configurées par l’administration.',
    important: false,
    changes: [
      'L’activation d’un forfait gratuit déclenche une notification configurée.',
      'La confirmation Stripe d’un abonnement payant déclenche la même notification.',
      'Les notifications n’affectent pas l’accès au forfait souscrit.',
    ],
  },
  {
    audience: 'admin',
    version: '1.17.0',
    date: '2026-09-06',
    title: 'Alertes sur les nouvelles souscriptions',
    summary: 'Le super-admin configure les notifications e-mail et Telegram envoyées pour chaque nouveau forfait.',
    important: false,
    changes: [
      'Les forfaits gratuits et les abonnements Stripe déclenchent la même alerte de souscription.',
      'Le destinataire e-mail, le jeton du bot Telegram et le chatID se règlent dans la rubrique Notifications.',
      'Le jeton Telegram enregistré reste masqué dans les réponses de l’administration.',
      'Les événements déjà traités ne génèrent pas une seconde alerte.',
    ],
  },
  {
    audience: 'app',
    version: '1.16.0',
    date: '2026-09-01',
    title: 'Une démonstration pilotée par son forfait',
    summary: 'Les capacités de la session temporaire utilisent désormais une configuration dédiée et cohérente sur tous les écrans.',
    important: false,
    changes: [
      'La durée d’inactivité, le nombre d’imports, la taille des fichiers et le stockage proviennent du forfait de démonstration.',
      'Les dispositions personnalisées, les playlists, la télécommande et le nombre de spectacles suivent les droits de ce forfait.',
      'Les limites affichées avant et après l’ouverture de la démonstration reflètent la configuration active.',
      'La démonstration reste distincte de l’offre gratuite permanente et des abonnements.',
    ],
  },
  {
    audience: 'admin',
    version: '1.16.0',
    date: '2026-09-01',
    title: 'Capacités configurables de la démonstration',
    summary: 'La démonstration publique dispose d’un forfait interne modifiable depuis le catalogue des forfaits.',
    important: false,
    changes: [
      'Le forfait Démonstration publique configure le stockage, la durée d’inactivité, le nombre d’imports et la taille maximale par fichier.',
      'Les cases de fonctionnalités et la limite de spectacles s’appliquent également aux sessions temporaires.',
      'Ce forfait protégé ne peut pas être supprimé, attribué à un client, publié comme tarif ou synchronisé avec Stripe.',
      'Les sessions existantes sont rattachées automatiquement à ce forfait lors de la migration.',
    ],
  },
  {
    audience: 'app',
    version: '1.15.0',
    date: '2026-09-01',
    title: 'Des fonctionnalités adaptées à chaque forfait',
    summary: 'Chaque forfait peut désormais définir l’accès aux dispositions personnalisées, aux playlists, à la télécommande et le nombre de spectacles.',
    important: false,
    changes: [
      'La modification et l’enregistrement des dispositions peuvent être activés séparément par forfait.',
      'Les playlists et la télécommande disposent chacune de leur propre droit d’accès.',
      'Le nombre de spectacles peut être limité ou rester illimité selon le forfait.',
      'Les contenus déjà enregistrés sont conservés lorsqu’un droit est retiré.',
    ],
  },
  {
    audience: 'admin',
    version: '1.15.0',
    date: '2026-09-01',
    title: 'Droits fonctionnels des forfaits',
    summary: 'L’éditeur de forfait contrôle maintenant trois fonctionnalités et la limite de spectacles.',
    important: false,
    changes: [
      'Trois cases activent les dispositions personnalisées, les playlists et la télécommande.',
      'Un champ numérique fixe le nombre maximal de spectacles ; une valeur vide signifie illimité.',
      'Les nouveaux droits sont exposés dans les API de compte et de catalogue public.',
      'Les forfaits existants conservent toutes les fonctions et restent illimités après la migration.',
    ],
  },
  {
    audience: 'app',
    version: '1.14.1',
    date: '2026-09-01',
    title: 'Une bibliothèque de démonstration complète',
    summary: 'Chacune des huit catégories de la démonstration contient désormais quinze vrais sons Freesound.',
    important: false,
    changes: [
      'La bibliothèque passe de seize à cent vingt sons Freesound CC0.',
      'Animaux, Bruitages, Drame, Joyeux, Effets, Ambiances, Transitions et Public contiennent exactement quinze morceaux chacune.',
      'Les préécoutes sont limitées à huit secondes et l’ensemble des médias occupe environ huit mégaoctets par session.',
      'Le catalogue peut être reconstruit avec un script qui conserve les sources, auteurs, licences, groupes et tags.',
    ],
  },
  {
    audience: 'app',
    version: '1.14.0',
    date: '2026-09-01',
    title: 'Une démo équipée de vrais sons',
    summary: 'La démonstration démarre avec seize sons Freesound réels, répartis dans huit catégories prêtes à explorer.',
    important: false,
    changes: [
      'Les anciens sons synthétiques et leurs trois catégories sont retirés de la démonstration.',
      'Huit catégories contiennent chacune deux sons : Animaux, Bruitages, Drame, Joyeux, Effets, Ambiances, Transitions et Public.',
      'Tous les morceaux fournis sont issus de Freesound sous licence CC0.',
      'Les tags, la description, la page source, l’identifiant Freesound et la mention de licence sont enregistrés avec chaque morceau.',
    ],
  },
  {
    audience: 'app',
    version: '1.13.0',
    date: '2026-09-01',
    title: 'Dispositions nommées et interface affinée',
    summary: 'Les dispositions personnalisées peuvent être enregistrées sous un nom et plusieurs commandes de l’espace de travail gagnent en clarté.',
    important: false,
    changes: [
      'Une disposition personnalisée peut être nommée, chargée et supprimée depuis l’éditeur.',
      'La grille interne est fixée à douze colonnes et le choix 6/8/12 est retiré.',
      'Les cartes de catégories conservent une forme carrée et leurs commandes sont placées près du titre.',
      'Les modes Noms et Tags utilisent un switch, avec plus d’espace entre Freesound et le raccourci.',
    ],
  },
  {
    audience: 'app',
    version: '1.12.0',
    date: '2026-09-01',
    title: 'Modules repliables',
    summary: 'La Playlist et les Actions de déclenchement peuvent être réduites en une barre discrète et restaurées à la demande.',
    important: false,
    changes: [
      'Une petite commande replie la Playlist ou les Actions de déclenchement sans modifier leur emplacement.',
      'Un module replié devient une barre de 34 pixels avec son icône, son titre et le compteur de la playlist.',
      'La playlist compacte utilise le même mécanisme et se rouvre automatiquement lors d’un ajout ou d’un dépôt.',
      'L’état de chaque module est mémorisé avec la disposition locale.',
    ],
  },
  {
    audience: 'app',
    version: '1.11.1',
    date: '2026-08-31',
    title: 'Catégories entièrement visibles',
    summary: 'Le bloc Catégories gagne une rangée afin que les cartes et leurs titres ne soient plus coupés.',
    important: false,
    changes: [
      'Le bloc Catégories occupe au minimum trois rangées dans chaque modèle de disposition.',
      'Les dispositions enregistrées avec l’ancienne hauteur sont adaptées automatiquement.',
      'Le Soundboard et les autres blocs situés dessous conservent tout l’espace restant.',
    ],
  },
  {
    audience: 'app',
    version: '1.11.0',
    date: '2026-08-31',
    title: 'Colonne gauche réorganisable',
    summary: 'Les actions, les lectures et la playlist peuvent désormais être placées dans la colonne gauche de l’espace de travail.',
    important: false,
    changes: [
      'La colonne gauche accepte les blocs Actions de déclenchement, Lectures en cours et Playlist.',
      'Les actions de déclenchement deviennent un bloc déplaçable dans l’éditeur de disposition.',
      'En Régie compacte, déplacer les lectures dans la colonne gauche y déplace aussi la playlist conditionnelle.',
      'Les blocs restants s’étendent automatiquement dans l’espace libéré sur la grille.',
      'Sur mobile, les actions restent dans le menu latéral et les autres blocs conservent leur ordre vertical.',
    ],
  },
  {
    audience: 'app',
    version: '1.10.0',
    date: '2026-08-31',
    title: 'Playlist en tiroir compact',
    summary: 'Un nouveau modèle réserve toute la colonne aux lectures et ouvre la playlist à la demande sous celles-ci.',
    important: false,
    changes: [
      'Le modèle Régie compacte affiche les lectures en cours sur toute la hauteur de la colonne droite.',
      'Un bouton fixé en bas ouvre ou masque la playlist et affiche son nombre de morceaux.',
      'Glisser un morceau sur ce bouton ouvre le tiroir et permet de l’ajouter directement.',
      'La hauteur et l’état du tiroir sont conservés localement pour chaque utilisateur.',
    ],
  },
  {
    audience: 'app',
    version: '1.9.0',
    date: '2026-08-31',
    title: 'Espace de travail réorganisable',
    summary: 'Les quatre zones principales peuvent être permutées et redimensionnées sur une grille, avec deux dispositions dédiées à la playlist.',
    important: false,
    changes: [
      'Les catégories, le soundboard, les lectures en cours et la playlist occupent quatre blocs indépendants.',
      'Les modèles Régie classique, Playlist verticale et Playlist principale changent immédiatement la disposition.',
      'La grille peut comporter six, huit ou douze colonnes et chaque bloc peut être redimensionné.',
      'La disposition est conservée localement pour chaque utilisateur et l’affichage mobile reste linéaire.',
    ],
  },
  {
    audience: 'app',
    version: '1.8.2',
    date: '2026-08-31',
    title: 'Insertion ciblée et grand bouton suivant',
    summary: 'Une seule position d’insertion s’ouvre pendant le glissement et les playlists peuvent afficher une grande commande Suivant.',
    important: false,
    changes: [
      'Seule la bande Insérer ici située sous le pointeur apparaît pendant un glisser-déposer.',
      'Le survol sans morceau déplacé ne révèle plus les bandes d’insertion.',
      'Une option de playlist affiche un bouton Morceau suivant sur toute la largeur du panneau.',
      'Le choix d’afficher cette commande est conservé avec chaque playlist enregistrée.',
    ],
  },
  {
    audience: 'app',
    version: '1.8.1',
    date: '2026-08-31',
    title: 'Rangées de playlist plus lisibles',
    summary: 'Les morceaux groupés partagent toute la largeur et les positions de déplacement restent visibles pendant le glisser-déposer.',
    important: false,
    changes: [
      'Deux, trois ou quatre morceaux se répartissent la largeur disponible sans défilement horizontal.',
      'Une infobulle affiche le titre complet lorsqu’il est tronqué.',
      'Toutes les bandes d’insertion apparaissent pendant le déplacement d’un morceau externe ou interne.',
      'Un morceau groupé peut être extrait et replacé seul ailleurs dans la playlist.',
      'Les légendes permanentes de glisser-déposer ont été supprimées.',
    ],
  },
  {
    audience: 'app',
    version: '1.8.0',
    date: '2026-08-31',
    title: 'Importer une arborescence de sons',
    summary: 'Un dossier et ses sous-dossiers peuvent devenir des catégories, des sous-catégories ou des tags au moment du dépôt.',
    important: false,
    changes: [
      'Le dépôt lit récursivement tous les fichiers audio d’un dossier.',
      'Une boîte de dialogue propose une catégorie par dossier, une sous-catégorie par dossier ou les noms des dossiers comme tags.',
      'Les catégories et sous-catégories portant déjà le même nom sont réutilisées dans leur destination.',
      'Les morceaux placés directement à la racine restent dans la catégorie active.',
    ],
  },
  {
    audience: 'app',
    version: '1.7.1',
    date: '2026-08-31',
    title: 'Réglettes fines et durées audio fiables',
    summary: 'Les lecteurs compacts utilisent des curseurs plus discrets et les imports enregistrent désormais la durée réelle des fichiers.',
    important: false,
    changes: [
      'Les pistes et poignées des réglettes de position et de volume sont affinées en mode compact.',
      'Les imports unitaires, multiples et SoundShow mesurent la durée du fichier avant son envoi.',
      'Les morceaux dont la durée était absente peuvent de nouveau être lus normalement avec SonoRiva Bridge.',
    ],
  },
  {
    audience: 'app',
    version: '1.7.0',
    date: '2026-08-31',
    title: 'Colonne de lecture compacte',
    summary: 'La colonne limite les lectures simultanées et réduit automatiquement la hauteur de ses lecteurs lorsque leur nombre augmente.',
    important: false,
    changes: [
      'Huit lectures simultanées sont autorisées par défaut, avec une limite réglable de une à seize par spectacle.',
      'À partir de cinq lecteurs par défaut, les cartes occupent environ deux fois moins de hauteur et placent leurs commandes à droite.',
      'Le seuil du mode compact est réglable de une à seize lectures.',
      'Le compteur de la colonne affiche le nombre actif et la limite.',
      'Les morceaux restent déclenchables par clic pendant la réorganisation des sous-catégories.',
    ],
  },
  {
    audience: 'app',
    version: '1.6.1',
    date: '2026-08-31',
    title: 'Tiroirs de sous-catégorie plus directs',
    summary: 'Un morceau peut être ajouté en le déposant dans le tiroir ouvert, dont les commandes et le compteur sont plus lisibles.',
    important: false,
    changes: [
      'Déposer un morceau dans un espace libre du tiroir ouvert l’ajoute à la sous-catégorie.',
      'Un macaron compact affiche le nombre de morceaux juste à gauche du titre de la tuile.',
      'Les commandes Modifier et Supprimer précèdent désormais le titre dans l’en-tête du tiroir.',
    ],
  },
  {
    audience: 'app',
    version: '1.6.0',
    date: '2026-08-31',
    title: 'Sous-catégories en tiroir',
    summary: 'Les morceaux peuvent être regroupés dans une tuile compacte qui ouvre son contenu dans un tiroir sous la grille.',
    important: false,
    changes: [
      'Déposer un morceau au centre d’un autre crée une sous-catégorie contenant les deux morceaux.',
      'Les bords gauche et droit restent des zones d’insertion avant et après.',
      'Une tuile d’une case affiche un petit titre, une mosaïque et le nombre de morceaux.',
      'Un clic ouvre ou ferme un tiroir pleine largeur sous la ligne de la tuile.',
      'Le nom, la couleur et la catégorie parente sont modifiables depuis la tuile ou le tiroir.',
      'Supprimer le groupe conserve les morceaux et la recherche les affiche directement.',
    ],
  },
  {
    audience: 'app',
    version: '1.5.0',
    date: '2026-08-31',
    title: 'Rangées de playlist simultanées',
    summary: 'Une rangée de playlist peut contenir plusieurs morceaux lancés ensemble, sans perdre les zones d’insertion entre les étapes.',
    important: false,
    changes: [
      'Déposer un morceau au centre d’une rangée l’ajoute au départ simultané.',
      'Déposer un morceau dans l’espace entre deux rangées le replace seul à cet endroit.',
      'La limite des groupes se règle de deux à huit morceaux dans les paramètres du spectacle.',
      'La playlist passe à la rangée suivante lorsque le dernier morceau de la rangée courante se termine.',
      'Pause, stop, suivant, aléatoire, boucle et fondu enchaîné agissent sur les rangées complètes.',
      'Les playlists existantes conservent leur ordre avec un morceau par rangée.',
    ],
  },
  {
    audience: 'app',
    version: '1.4.0',
    date: '2026-08-31',
    title: 'Clavier étendu et dernier lecteur',
    summary: 'Les morceaux visibles reçoivent des touches de 1 à 9 puis de A à Z, tandis que la recherche et le retrait du dernier lecteur disposent de commandes corrigées.',
    important: false,
    changes: [
      'Retour arrière retire immédiatement le dernier lecteur et Maj + Retour arrière le retire avec son fondu.',
      'Les deux commandes de retour arrière restent configurables par spectacle.',
      'Les 35 premiers morceaux visibles utilisent successivement les touches 1 à 9 puis A à Z.',
      'L’action du déclenchement clavier se règle à côté des actions des clics gauche et droit.',
      'Le raccourci de recherche place désormais réellement le curseur dans le champ.',
      'La recherche affiche ⌘ K sur macOS et Ctrl K sur Windows.',
    ],
  },
  {
    audience: 'app',
    version: '1.3.0',
    date: '2026-08-31',
    title: 'Raccourcis de régie configurables',
    summary: 'La navigation, les départs, le chargement, le routage et le volume maître sont pilotables au clavier avec des affectations propres à chaque spectacle.',
    important: false,
    changes: [
      'Tab et Ctrl + Tab parcourent les catégories dans les deux sens.',
      'Les touches 1 à 9 démarrent les morceaux visibles et leur variante avec Ctrl lance un fondu enchaîné.',
      'AltGr charge tous les morceaux de la catégorie actuelle dans le cache.',
      'Maj maintenue route les nouveaux départs vers la sortie secondaire et Verr. Maj bascule durablement la sortie.',
      'Les touches + et - règlent le volume maître, avec un pas accéléré lorsque Ctrl est maintenu.',
      'Chaque nouvelle combinaison peut être réaffectée dans les paramètres du spectacle.',
    ],
  },
  {
    audience: 'app',
    version: '1.2.0',
    date: '2026-08-31',
    title: 'Sélection et édition de lot',
    summary: 'Plusieurs morceaux peuvent être sélectionnés par clic ou par rectangle puis modifiés ensemble.',
    important: false,
    changes: [
      'Un bouton du tableau de bord active la sélection multiple des morceaux.',
      'Les cartes sont sélectionnables individuellement ou avec un rectangle tracé à la souris.',
      'Une barre contextuelle permet de tout sélectionner, d’effacer la sélection ou d’ouvrir l’édition de lot.',
      'La catégorie, la couleur, les tags, le volume, la boucle et les fondus peuvent être appliqués en une opération.',
      'Les tags peuvent être ajoutés, retirés ou remplacés sur toute la sélection.',
    ],
  },
  {
    audience: 'app',
    version: '1.1.0',
    date: '2026-08-31',
    title: 'Retrouver les sons par tags',
    summary: 'Les morceaux peuvent être décrits par des tags et la recherche choisit explicitement entre les noms et ces tags.',
    important: false,
    changes: [
      'Les réglages d’un morceau permettent d’ajouter et de supprimer jusqu’à 30 tags.',
      'La barre de recherche propose les modes Noms et Tags, avec la recherche par nom sélectionnée par défaut.',
      'Une recherche composée de plusieurs mots peut correspondre à plusieurs tags du même morceau.',
      'Les tags Freesound sont conservés lors de l’import d’un son.',
    ],
  },
  {
    audience: 'app',
    version: '1.0.0',
    date: '2026-08-29',
    title: 'SonoRiva entre en scène',
    summary: 'L’application, le site public et le Bridge adoptent intégralement la nouvelle identité SonoRiva.',
    important: true,
    changes: [
      'Le nom SonoRiva et le monogramme SR remplacent l’ancienne identité dans toute l’interface.',
      'Une nouvelle palette aqua habille l’application, la documentation, les e-mails et le site public.',
      'Les adresses publiques deviennent sonoriva.fr et app.sonoriva.fr.',
      'SonoRiva Bridge utilise son propre protocole natif, ses propres identifiants système et de nouveaux paquets.',
      'Les clés locales, caches et sessions repartent sur des identifiants exclusivement SonoRiva.',
    ],
  },
  {
    audience: 'app',
    version: '0.24.0',
    date: '2026-08-29',
    title: 'Sorties audio selon le forfait',
    summary: 'La gestion des sorties audio est réservée aux forfaits payants actifs et son accès est présenté directement dans le header.',
    important: false,
    changes: [
      'Le module des sorties audio est placé à gauche du volume du son suivant sur toutes les largeurs d’écran.',
      'Le forfait gratuit et la démonstration affichent un bouton d’accès aux forfaits à la place du sélecteur.',
      'Pendant la période d’essai, le module renvoie vers la gestion de l’abonnement et indique que la fonction sera disponible après l’essai.',
      'Les paramètres masquent également les contrôles avancés lorsque le forfait ne les inclut pas.',
      'La sortie système par défaut reste utilisée lorsque la gestion avancée n’est pas disponible.',
    ],
  },
  {
    audience: 'app',
    version: '0.23.0',
    date: '2026-08-29',
    title: 'Tableau des sorties et Bridge autonome',
    summary: 'Les sorties disposent d’une réglette lisible au-dessus du header et SonoRiva Bridge peut désormais installer ses mises à jour signées.',
    important: true,
    changes: [
      'Une réglette fine affiche côte à côte le nom complet et la couleur de chaque sortie physique.',
      'La sortie principale est identifiée explicitement dans cette réglette.',
      'Le sélecteur de sortie du header est élargi et la légende compacte qui le comprimait a été retirée.',
      'SonoRiva Bridge 0.5.0 vérifie et installe automatiquement les versions signées publiées sur GitHub.',
      'Une mise à jour du Bridge est différée si une lecture audio est active pendant son téléchargement.',
    ],
  },
  {
    audience: 'app',
    version: '0.22.0',
    date: '2026-08-29',
    title: 'Des sorties audio plus lisibles',
    summary: 'La régie distingue clairement la sortie principale, les sorties alternatives et l’espace disque utilisé par le Bridge.',
    important: false,
    changes: [
      'Le grand Play est entouré par la couleur de la sortie principale.',
      'Les petits Plays affichent uniquement les autres sorties et sont alignés sur le bas du grand bouton.',
      'Le header affiche le code couleur et le nom de chaque sortie physique disponible.',
      'La fenêtre du Bridge affiche le nombre de fichiers et leur espace disque total.',
      'SonoRiva Bridge 0.4.0 utilise un fond DMG bilingue qui illustre l’installation et l’ouverture d’une application non notariée.',
    ],
  },
  {
    audience: 'app',
    version: '0.21.0',
    date: '2026-08-29',
    title: 'Une sortie par lecture',
    summary: 'SonoRiva Bridge peut lancer chaque morceau sur une sortie précise et déplacer une lecture active vers un autre périphérique.',
    important: true,
    changes: [
      'Lorsque plusieurs sorties physiques sont disponibles, chaque morceau affiche un petit bouton Play coloré par sortie.',
      'Le grand bouton Play conserve le comportement de la sortie principale.',
      'Une LED colorée dans chaque lecteur actif indique sa sortie et ouvre le choix des autres sorties.',
      'Le passage sur une autre sortie conserve la position, la pause, la boucle et le volume de la lecture.',
      'Cette fonction nécessite SonoRiva Bridge 0.3.0 ou une version ultérieure.',
    ],
  },
  {
    audience: 'app',
    version: '0.20.0',
    date: '2026-08-29',
    title: 'Connexion rapide au Bridge',
    summary: 'La barre de régie détecte SonoRiva Bridge et permet de l’associer ou de l’activer sans ouvrir les paramètres.',
    important: false,
    changes: [
      'Une LED indique si le Bridge est fermé, détecté, prêt ou actif.',
      'Un bouton adapte son action pour associer, ouvrir, activer ou désactiver le Bridge.',
      'Un second bouton relance immédiatement la détection locale.',
      'La détection est actualisée automatiquement toutes les cinq secondes pour les forfaits disposant du Bridge.',
    ],
  },
  {
    audience: 'app',
    version: '0.19.1',
    date: '2026-08-29',
    title: 'Correction de l’association du Bridge',
    summary: 'Le navigateur récupère maintenant correctement sa clé locale lorsque SonoRiva Bridge accepte une association.',
    important: true,
    changes: [
      'La clé locale est renvoyée au navigateur avant d’être effacée du ticket à usage unique.',
      'La consommation du ticket et l’effacement de la clé sont exécutés dans une transaction atomique.',
      'Une seconde récupération du même ticket reste refusée.',
    ],
  },
  {
    audience: 'app',
    version: '0.19.0',
    date: '2026-08-29',
    title: 'La sortie audio dans la barre de régie',
    summary: 'Un grand sélecteur placé à côté du volume du son suivant permet de voir et de changer immédiatement la sortie principale.',
    important: false,
    changes: [
      'Le périphérique actif est visible en permanence dans la barre supérieure de la régie principale.',
      'Le sélecteur pilote directement Web Audio ou la sortie principale de SonoRiva Bridge selon le moteur actif.',
      'Un état rouge et un symbole d’alerte signalent une sortie déconnectée ou un Bridge indisponible.',
      'La liste se met à jour lorsque les périphériques audio ou les réglages de sortie changent.',
    ],
  },
  {
    audience: 'app',
    version: '0.18.0',
    date: '2026-08-29',
    title: 'SonoRiva Bridge dans les forfaits payants',
    summary: 'L’association, l’utilisation et le téléchargement depuis SonoRiva sont maintenant réservés aux comptes disposant d’un forfait payant actif.',
    important: true,
    changes: [
      'Les forfaits gratuits conservent le moteur Navigateur complet mais n’affichent plus les commandes du Bridge.',
      'Les comptes en essai sur un forfait payant disposent du Bridge pendant leur période d’essai.',
      'L’API contrôle le forfait avant une association, une synchronisation ou un téléchargement audio par le Bridge.',
      'Une association locale est oubliée lorsque le compte ne dispose plus du droit Bridge.',
      'Le site SonoRiva indique dans chaque offre si SonoRiva Bridge est inclus.',
    ],
  },
  {
    audience: 'app',
    version: '0.17.0',
    date: '2026-08-29',
    title: 'SonoRiva Bridge pour Windows',
    summary: 'Le moteur audio natif facultatif est maintenant distribué pour Windows x64 en plus des deux architectures macOS.',
    important: true,
    changes: [
      'Un installateur Windows x64 est disponible dans la publication GitHub de SonoRiva Bridge.',
      'L’association avec le navigateur utilise le même lien natif et le même serveur local que sur macOS.',
      'Les clés du bridge sont conservées dans le Gestionnaire d’identification Windows.',
      'Le cache audio, la sortie principale et la préécoute fonctionnent indépendamment du cache du navigateur.',
      'L’application web reste entièrement utilisable sans installer ni sélectionner le bridge.',
    ],
  },
  {
    audience: 'app',
    version: '0.16.1',
    date: '2026-08-29',
    title: 'Téléchargement du bridge pour Mac Intel et Apple Silicon',
    summary: 'SonoRiva Bridge est distribué depuis GitHub dans deux paquets adaptés aux architectures macOS.',
    important: true,
    changes: [
      'Le lien de téléchargement se trouve dans la rubrique Moteur et sorties audio des paramètres.',
      'Un paquet aarch64 est proposé pour les Mac Apple Silicon.',
      'Un paquet x64 est proposé pour les Mac Intel.',
      'Les paquets utilisent une signature ad hoc et ne sont pas notariés par Apple.',
    ],
  },
  {
    audience: 'app',
    version: '0.16.0',
    date: '2026-08-29',
    title: 'SonoRiva Bridge pour macOS',
    summary: 'Un moteur audio natif facultatif ajoute un cache local et des sorties indépendantes sans retirer le mode Web Audio.',
    important: true,
    changes: [
      'Le moteur Navigateur reste actif par défaut et conserve toutes les fonctions existantes.',
      'Le bouton Connecter le bridge ouvre l’application macOS au moyen d’un lien natif à usage unique.',
      'Le bridge conserve les fichiers audio compressés dans son propre cache et les lit sans passer par le cache du navigateur.',
      'La régie principale et la préécoute disposent de sélections de sortie distinctes dans le bridge.',
      'Les lectures, fondus, pauses, volumes, boucles, déplacements et arrêts sont pilotés depuis l’interface web.',
      'Les bridges associés peuvent être consultés et révoqués depuis les paramètres SonoRiva.',
    ],
  },
  {
    audience: 'app',
    version: '0.15.0',
    date: '2026-08-28',
    title: 'Sélection de la sortie audio',
    summary: 'La régie peut maintenant utiliser un périphérique de sortie distinct de la sortie système.',
    important: true,
    changes: [
      'La rubrique Sortie audio des paramètres affiche les périphériques de lecture disponibles.',
      'Le périphérique choisi reçoit les sons de la régie et les préécoutes de l’éditeur et de Freesound.',
      'La sélection est enregistrée localement sur l’appareil utilisé.',
      'La sortie système est rétablie si le périphérique enregistré n’est plus disponible.',
      'Les navigateurs sans sélection de sortie Web Audio continuent d’utiliser la sortie système.',
    ],
  },
  {
    audience: 'app',
    version: '0.14.0',
    date: '2026-08-28',
    title: 'Forfait gratuit sans carte bancaire',
    summary: 'Un forfait à 0 € peut maintenant être activé sans créer de client ni d’abonnement Stripe.',
    important: true,
    changes: [
      'L’inscription sur un forfait gratuit ouvre immédiatement l’espace sans redirection vers Stripe.',
      'Le quota de stockage configuré sur le forfait gratuit s’applique dès la création du compte.',
      'Le passage ultérieur vers un forfait payant reste disponible depuis la rubrique Offre et stockage.',
      'Les forfaits payants conservent leur parcours Checkout avec essai et moyen de paiement.',
    ],
  },
  {
    audience: 'admin',
    version: '0.14.0',
    date: '2026-08-28',
    title: 'Gestion des offres gratuites',
    summary: 'Les tarifs à 0 € identifient désormais les forfaits activés sans Stripe.',
    important: false,
    changes: [
      'Un forfait est gratuit lorsqu’au moins un prix est renseigné et que tous ses prix renseignés valent 0 €.',
      'Un prix vide continue de rendre la périodicité correspondante indisponible.',
      'Les activations gratuites sont inscrites dans le journal d’audit du compte.',
      'Les forfaits comportant un prix positif restent exclusivement associés au parcours Stripe Checkout.',
    ],
  },
  {
    audience: 'app',
    version: '0.13.0',
    date: '2026-08-27',
    title: 'Inscription avec moyen de paiement',
    summary: 'La création du compte enregistre le forfait et le moyen de paiement sur Stripe avant le début de l’essai.',
    important: true,
    changes: [
      'Le forfait et la périodicité se choisissent directement dans le formulaire d’inscription.',
      'La validation du compte ouvre immédiatement la page Checkout hébergée par Stripe.',
      'L’essai commence après la validation de Checkout et ne déclenche aucun paiement immédiat.',
      'La première échéance Stripe intervient à la fin de la durée d’essai configurée pour le forfait.',
    ],
  },
  {
    audience: 'app',
    version: '0.12.0',
    date: '2026-08-26',
    title: 'Abonnement Stripe',
    summary: 'Les propriétaires d’un espace peuvent souscrire et gérer leur abonnement depuis les paramètres.',
    important: false,
    changes: [
      'Le forfait et la périodicité mensuelle ou annuelle se sélectionnent dans la rubrique Offre et stockage.',
      'Le paiement et la saisie du moyen de paiement utilisent la page Checkout hébergée par Stripe.',
      'Le portail de facturation donne accès aux factures, au moyen de paiement et à la résiliation.',
      'Le forfait, le quota et l’accès sont actualisés après confirmation du changement par Stripe.',
    ],
  },
  {
    audience: 'admin',
    version: '0.12.0',
    date: '2026-08-26',
    title: 'Intégration Stripe Billing',
    summary: 'Le catalogue, les abonnements et les droits SonoRiva sont reliés à Stripe Billing.',
    important: true,
    changes: [
      'Chaque forfait peut créer un produit et ses tarifs mensuel et annuel dans l’environnement Stripe configuré.',
      'Les montants modifiés créent de nouveaux tarifs sans altérer les abonnements historiques.',
      'Les webhooks signés synchronisent les abonnements, périodes, quotas et états d’accès de manière idempotente.',
      'Les suspensions administratives restent prioritaires sur les événements de facturation.',
      'Un rapprochement périodique et une commande manuelle corrigent les écarts avec Stripe.',
    ],
  },
  {
    audience: 'app',
    version: '0.11.0',
    date: '2026-08-26',
    title: 'Mises à jour automatiques',
    summary: 'Un réglage permet d’installer les nouvelles versions sans afficher de demande de confirmation.',
    important: false,
    changes: [
      'Le mode automatique se règle depuis les paramètres de l’application.',
      'Une version en attente est installée dès qu’aucun son n’est en lecture.',
      'Les notifications et l’ouverture automatique des notes sont masquées en mode automatique.',
      'La bannière de mise à jour reste disponible lorsque le mode automatique est désactivé.',
      'Les nouveautés affichées concernent uniquement les fonctions de la régie.',
    ],
  },
  {
    audience: 'admin',
    version: '0.11.0',
    date: '2026-08-26',
    title: 'Documentation administrative séparée',
    summary: 'La documentation et les versions commerciales sont maintenant regroupées dans le dashboard protégé.',
    important: false,
    changes: [
      'Une rubrique Documentation est disponible dans le dashboard d’administration.',
      'Les notes de version commerciales sont retirées de la documentation publique.',
      'Les évolutions de l’application et de l’administration utilisent deux flux distincts.',
    ],
  },
  {
    audience: 'app',
    version: '0.10.1',
    date: '2026-08-25',
    title: 'Démonstration sans interruption',
    summary: 'Les messages liés aux mises à jour sont désormais réservés aux espaces personnels.',
    important: false,
    changes: [
      'La bannière de mise à jour n’apparaît plus dans une démonstration.',
      'La fenêtre automatique et la rubrique Nouveautés sont masquées dans une démonstration.',
      'Les comptes personnels continuent de recevoir les informations de version.',
    ],
  },
  {
    audience: 'app',
    version: '0.10.0',
    date: '2026-08-25',
    title: 'Essai immédiat sans compte',
    summary: 'Une démonstration temporaire permet maintenant d’utiliser SonoRiva immédiatement, sans inscription.',
    important: false,
    changes: [
      'Chaque visiteur dispose d’un espace de démonstration isolé et de trois sons préchargés.',
      'La démonstration accepte 15 fichiers importés de 5 Mo maximum chacun.',
      'Les données temporaires sont supprimées après 24 heures d’inactivité.',
      'La démonstration peut être réinitialisée ou remplacée par un espace personnel depuis l’application.',
    ],
  },
  {
    audience: 'admin',
    version: '0.9.0',
    date: '2026-08-25',
    title: 'Forfaits synchronisés avec le site',
    summary: 'Les forfaits publics du dashboard alimentent désormais automatiquement le bloc tarifaire WordPress.',
    important: false,
    changes: [
      'Chaque forfait dispose de réglages de visibilité, de mise en avant et d’ordre d’affichage.',
      'Une API publique limitée expose les forfaits actifs destinés au site de présentation.',
      'Le forfait par défaut actuel est publié automatiquement lors de la mise à jour.',
      'Le bloc WordPress conserve la dernière réponse valide lorsque l’API est indisponible.',
    ],
  },
  {
    audience: 'admin',
    version: '0.8.0',
    date: '2026-08-25',
    title: 'Gestion complète des forfaits',
    summary: 'Le tableau de bord super-administrateur centralise les prix, quotas et règles de chaque forfait.',
    important: false,
    changes: [
      'La vue Forfaits affiche les prix mensuels et annuels, le quota, l’essai et le nombre de comptes attribués.',
      'Un forfait peut être créé, modifié ou dupliqué depuis le catalogue commercial.',
      'Un forfait inutilisé peut être supprimé s’il n’est pas défini par défaut.',
      'La fiche d’un compte résume le prix et les limites du forfait sélectionné.',
    ],
  },
  {
    audience: 'app',
    version: '0.7.0',
    date: '2026-08-25',
    title: 'Réinitialisation du mot de passe',
    summary: 'La page de connexion permet désormais de définir un nouveau mot de passe par e-mail.',
    important: false,
    changes: [
      'Le lien « Mot de passe oublié ? » est disponible sur la page de connexion.',
      'Le lien reçu par e-mail expire après 30 minutes et ne fonctionne qu’une fois.',
      'La modification du mot de passe ferme toutes les sessions précédentes.',
    ],
  },
  {
    audience: 'app',
    version: '0.6.0',
    date: '2026-08-25',
    title: 'SonoRiva sur son propre domaine',
    summary: 'Le site et l’application utilisent désormais le domaine sonoriva.fr.',
    important: true,
    changes: [
      'Le site de présentation est disponible sur sonoriva.fr.',
      'L’application est disponible sur app.sonoriva.fr.',
      'La documentation reste intégrée à l’application sous /docs/.',
      'Les liens Community et GitHub ont été retirés du site de présentation.',
    ],
  },
  {
    audience: 'admin',
    version: '0.5.0',
    date: '2026-08-25',
    title: 'Administration commerciale',
    summary: 'SonoRiva intègre désormais la gestion de ses comptes, forfaits, essais, quotas et rôles administratifs.',
    important: true,
    changes: [
      'Le tableau de bord commercial est disponible sous /admin.',
      'Les forfaits définissent le stockage, la durée d’essai et les prix mensuel et annuel.',
      'Les comptes disposent d’états d’accès distincts de leur abonnement.',
      'Les modifications administratives sont consignées dans un journal d’audit.',
    ],
  },
  {
    audience: 'app',
    version: '0.4.0',
    date: '2026-08-25',
    title: 'SonoRiva entre en scène',
    summary: 'SonoRiva devient la nouvelle identité de la régie, avec une signature claire : Play sound. Play the scene.',
    important: true,
    changes: [
      'Toute l’application adopte le nom SonoRiva et le monogramme SR.',
      'L’application et sa documentation disposent de nouvelles adresses SonoRiva.',
      'Les préférences, sessions et sons hors ligne existants sont repris automatiquement sur l’ancienne adresse.',
      'L’ancienne adresse reste disponible pendant la transition.',
    ],
  },
  {
    audience: 'app',
    version: '0.3.0',
    date: '2026-08-25',
    title: 'La documentation entre en scène',
    summary: 'SonoRiva dispose désormais d’un centre d’aide public, consultable depuis l’application et le site de présentation.',
    important: true,
    changes: [
      'Une documentation moderne accompagne la prise en main et la préparation des spectacles.',
      'Les guides couvrent l’import, l’organisation, le mode hors ligne et la télécommande.',
      'Une section de dépannage et une référence des formats sont disponibles sans connexion au compte.',
      'Chaque note de version peut renvoyer vers une présentation détaillée.',
    ],
  },
  {
    audience: 'app',
    version: '0.2.0',
    date: '2026-08-25',
    title: 'Des mises à jour plus sereines',
    summary: 'SonoRiva présente désormais clairement ses nouveautés et laisse la régie choisir quand actualiser l’application.',
    important: true,
    changes: [
      'Une fenêtre Nouveautés présente les évolutions importantes.',
      'Un badge permet de retrouver les notes de version depuis les paramètres.',
      'Les mises à jour de la PWA attendent que la régie soit disponible avant de se recharger.',
      'La version déployée est visible dans l’application et dans le contrôle de santé.',
    ],
  },
];

export const APP_RELEASES = RELEASES.filter((release) => release.audience === 'app');
export const ADMIN_RELEASES = RELEASES.filter((release) => release.audience === 'admin');

export const CURRENT_RELEASE = APP_RELEASES[0]!;
export const CURRENT_VERSION = CURRENT_RELEASE.version;

export function compareVersions(left: string, right: string): number {
  const leftParts = parseVersion(left);
  const rightParts = parseVersion(right);
  for (let index = 0; index < 3; index += 1) {
    const difference = leftParts[index] - rightParts[index];
    if (difference !== 0) return Math.sign(difference);
  }
  return 0;
}

export function releasesAfter(version: string | null): AppRelease[] {
  if (!version) return APP_RELEASES;
  return APP_RELEASES.filter((release) => compareVersions(release.version, version) > 0);
}

export function releaseExists(version: string): boolean {
  return APP_RELEASES.some((release) => release.version === version);
}

function parseVersion(version: string): [number, number, number] {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(version);
  if (!match) return [0, 0, 0];
  return [Number(match[1]), Number(match[2]), Number(match[3])];
}
